language: generic
addons:
  ssh_known_hosts: 125.212.227.42
before_install:
- sudo apt-get update
- sudo apt-get install -y nodejs npm --no-install-recommends
- sudo rm -rf /usr/bin/nodejs
- sudo ln -s /home/travis/.nvm/versions/node/v8.9.1/bin/node /usr/bin/nodejs
- ls -lash /usr/bin/nodejs
- sudo npm install -g hexo
- openssl aes-256-cbc -K $encrypted_38ebcd8c19a4_key -iv $encrypted_38ebcd8c19a4_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: npm install && hexo generate && scp -r $TRAVIS_BUILD_DIR/public/* hoangnm@125.212.227.42:/home/hoangnm/web/mystories.vn/html
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: scp -r $TRAVIS_BUILD_DIR/* hoangnm@125.212.227.42:/home/hoangnm/web/mystories.vn/html
    on:
      branch: master
